# Activity Time: Case Analysis

Maria is a 25-year-old US Army veteran, newly returned to the civilian workforce. She has recently completed a six-year commitment with the Army. During her time in the Army, she worked in supply management and logistics. She has decided to pursue a degree in Management Systems and Information Technology.

Maria has asked you to use your data skills to help her search for the best school for her. She is willing to relocate anywhere in the continental United States, but she has a few criteria that her ideal schools must satisfy: 

1. Safety of the city
2. Schools should be offering a degree in IT
3. Ranking of the school

Please refer to the following datasets

[CollegeScorecard2](./CollegeScorecard2.xlsx)

[Crime_2015](./Crime_2015.xlsx)

# Your Next Steps
1. **Clean the data for**

    a. Any duplicates

    b. Missing Values

    c. Inconsistent values
    

2. **Data Enrichment**

    a. Calculate School Ranking

    b. Calculate the overall crime rate


3. **Structure the Data**: Merge the tables and produce the dataset which must have:

    a. Top 5 schools on rankings for It college

    b. Be in a city that is below 50th percentile in overall crime
    
    c. Remove unecessary columns

The first thing we need to do is extract the data from the spreadsheets into a dataframe for manipulation

In [25]:
# Pull the data from the spreadsheet into a dataframe

import os
import pandas as pd

cwd = os.getcwd()

collegescore_file = 'CollegeScorecard2.xlsx'
crime2015_file = 'Crime_2015.xlsx'

collegescore_path = os.path.join(cwd, collegescore_file)
collegescore_df = pd.read_excel(path)

crime2015_path = os.path.join(cwd, crime2015_file)
crime2015_df = pd.read_excel(crime2015_path)

Next we can explore the data to gain some insights

In [26]:
print("College Score:")
print(collegescore_df.shape)
print("Crime 2015: ")
print(crime2015_df.shape)

College Score:
(31, 9)
Crime 2015:
(37, 8)

This tells us that the college score dataset has 31 instances and 9 attributes, and the crime 2015 dataset has 37 instances and 8 attributes.

In [27]:
collegescore_df.head() # preview the top 5 rows

,uid,RANK,UNIVERSITY,CITY,Courses,AcademicScore,Staff/TeacherRatio,Citation Index,NPCURL
0,10023,5,Cornell University,Ithaca,IT/Management,7.0,8.0,5.0,galileo.aamu.edu/netpricecalculator/npcalc.htm
1,10034,6,University of Washington,Seattle ...,IT,9.0,8.0,9.0,www.collegeportraits.org/AL/UAB/estimator/agree
2,10294,7,Columbia University in the City of New York,New York City,Management,6.0,7.0,7.0,tcc.noellevitz.com/(S(miwoihs5stz5cpyifh4nczu0...
3,10388,10,University of Minnesota-Twin Cities,Minneapolis ...,Medical,5.0,6.0,7.0,finaid.uah.edu/
4,10524,12,University of Pennsylvania,Philadelphia,Architecture,6.0,4.0,6.0,www.alasu.edu/cost-aid/forms/calculator/index....

In [28]:
crime2015_df.head() # preview the top 5 rows

,CITY,ViolentCrime,Murder,Robbery,PropertyCrime,Burglary,Theft,MotorVehicleTheft
0,Ithaca,1160.0,15.1,122.2,4701.9,1179.5,3356.0,166.3
1,Seattle ...,1070.1,7.6,126.6,4233.9,801.2,2937.7,495.1
2,New York City,936.4,4.5,120.1,4565.9,1167.0,3083.7,315.2
3,Minneapolis ...,901.5,19.3,247.0,2935.8,700.9,1769.3,465.7
4,Philadelphia,825.4,5.5,147.8,4529.4,966.8,3223.1,339.6

In [29]:
collegescore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   uid                 31 non-null     int64
 1   RANK                31 non-null     int64
 2   UNIVERSITY          31 non-null     object
 3   CITY                31 non-null     object
 4   Courses             30 non-null     object
 5   AcademicScore       22 non-null     float64
 6   Staff/TeacherRatio  22 non-null     float64
 7   Citation Index      20 non-null     float64
 8   NPCURL              31 non-null     object
dtypes: float64(3), int64(2), object(4)
memory usage: 2.3+ KB

From the summary of data, we can see there is some missing values. Specifically, we can see missing values for courses, academic score, staff/teachRatio, and Citation Index.