<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [36]:
%pip install pandas
%pip install matplotlib

Requirement already satisfied: pandas in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (2.4.1)
Requirement already satisfied: packaging>=20.0 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/apaquette/Documents/Education/NPower-Junior-Data-Analyst/.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [37]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [38]:
# Write your code here
df.dtypes

ResponseId               int64
MainBranch                 str
Age                        str
Employment                 str
RemoteWork                 str
                        ...
JobSatPoints_11        float64
SurveyLength               str
SurveyEase                 str
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

In [39]:
df.shape

(65437, 114)

In [40]:
for column in df.isnull().columns.values.tolist():
    print(df[column].isnull().value_counts())
    print("")

ResponseId
False    65437
Name: count, dtype: int64

MainBranch
False    65437
Name: count, dtype: int64

Age
False    65437
Name: count, dtype: int64

Employment
False    65437
Name: count, dtype: int64

RemoteWork
False    54806
True     10631
Name: count, dtype: int64

Check
False    65437
Name: count, dtype: int64

CodingActivities
False    54466
True     10971
Name: count, dtype: int64

EdLevel
False    60784
True      4653
Name: count, dtype: int64

LearnCode
False    60488
True      4949
Name: count, dtype: int64

LearnCodeOnline
False    49237
True     16200
Name: count, dtype: int64

TechDoc
False    40897
True     24540
Name: count, dtype: int64

YearsCode
False    59869
True      5568
Name: count, dtype: int64

YearsCodePro
False    51610
True     13827
Name: count, dtype: int64

DevType
False    59445
True      5992
Name: count, dtype: int64

OrgSize
False    47480
True     17957
Name: count, dtype: int64

PurchaseInfluence
False    47406
True     18031
Name: count, dtype: int64

BuyNewTool
False    45181
True     20256
Name: count, dtype: int64

BuildvsBuy
False    43358
True     22079
Name: count, dtype: int64

TechEndorse
False    43668
True     21769
Name: count, dtype: int64

Country
False    58930
True      6507
Name: count, dtype: int64

Currency
False    46684
True     18753
Name: count, dtype: int64

CompTotal
False    33740
True     31697
Name: count, dtype: int64

LanguageHaveWorkedWith
False    59745
True      5692
Name: count, dtype: int64

LanguageWantToWorkWith
False    55752
True      9685
Name: count, dtype: int64

LanguageAdmired
False    50872
True     14565
Name: count, dtype: int64

DatabaseHaveWorkedWith
False    50254
True     15183
Name: count, dtype: int64

DatabaseWantToWorkWith
False    42558
True     22879
Name: count, dtype: int64

DatabaseAdmired
False    38557
True     26880
Name: count, dtype: int64

PlatformHaveWorkedWith
False    42366
True     23071
Name: count, dtype: int64

PlatformWantToWorkWith
False    34532
True     30905
Name: count, dtype: int64

PlatformAdmired
True     34060
False    31377
Name: count, dtype: int64

WebframeHaveWorkedWith
False    45161
True     20276
Name: count, dtype: int64

WebframeWantToWorkWith
False    38535
True     26902
Name: count, dtype: int64

WebframeAdmired
False    34943
True     30494
Name: count, dtype: int64

EmbeddedHaveWorkedWith
True     43223
False    22214
Name: count, dtype: int64

EmbeddedWantToWorkWith
True     47837
False    17600
Name: count, dtype: int64

EmbeddedAdmired
True     48704
False    16733
Name: count, dtype: int64

MiscTechHaveWorkedWith
False    39443
True     25994
Name: count, dtype: int64

MiscTechWantToWorkWith
False    32964
True     32473
Name: count, dtype: int64

MiscTechAdmired
True     35841
False    29596
Name: count, dtype: int64

ToolsTechHaveWorkedWith
False    52482
True     12955
Name: count, dtype: int64

ToolsTechWantToWorkWith
False    46084
True     19353
Name: count, dtype: int64

ToolsTechAdmired
False    43997
True     21440
Name: count, dtype: int64

NEWCollabToolsHaveWorkedWith
False    57592
True      7845
Name: count, dtype: int64

NEWCollabToolsWantToWorkWith
False    52087
True     13350
Name: count, dtype: int64

NEWCollabToolsAdmired
False    50711
True     14726
Name: count, dtype: int64

OpSysPersonal use
False    58174
True      7263
Name: count, dtype: int64

OpSysProfessional use
False    52973
True     12464
Name: count, dtype: int64

OfficeStackAsyncHaveWorkedWith
False    48093
True     17344
Name: count, dtype: int64

OfficeStackAsyncWantToWorkWith
False    38966
True     26471
Name: count, dtype: int64

OfficeStackAsyncAdmired
False    37204
True     28233
Name: count, dtype: int64

OfficeStackSyncHaveWorkedWith
False    55545
True      9892
Name: count, dtype: int64

OfficeStackSyncWantToWorkWith
False    46711
True     18726
Name: count, dtype: int64

OfficeStackSyncAdmired
False    44712
True     20725
Name: count, dtype: int64

AISearchDevHaveWorkedWith
False    44453
True     20984
Name: count, dtype: int64

AISearchDevWantToWorkWith
False    36701
True     28736
Name: count, dtype: int64

AISearchDevAdmired
False    35543
True     29894
Name: count, dtype: int64

NEWSOSites
False    60286
True      5151
Name: count, dtype: int64

SOVisitFreq
False    59536
True      5901
Name: count, dtype: int64

SOAccount
False    59560
True      5877
Name: count, dtype: int64

SOPartFreq
False    45237
True     20200
Name: count, dtype: int64

SOHow
False    58962
True      6475
Name: count, dtype: int64

SOComm
False    59163
True      6274
Name: count, dtype: int64

AISelect
False    60907
True      4530
Name: count, dtype: int64

AISent
False    45873
True     19564
Name: count, dtype: int64

AIBen
False    36894
True     28543
Name: count, dtype: int64

AIAcc
False    37302
True     28135
Name: count, dtype: int64

AIComplex
False    37021
True     28416
Name: count, dtype: int64

AIToolCurrently Using
False    35072
True     30365
Name: count, dtype: int64

AIToolInterested in Using
True     34746
False    30691
Name: count, dtype: int64

AIToolNot interested in Using
True     41023
False    24414
Name: count, dtype: int64

AINextMuch more integrated
True     51999
False    13438
Name: count, dtype: int64

AINextNo change
True     52939
False    12498
Name: count, dtype: int64

AINextMore integrated
True     41009
False    24428
Name: count, dtype: int64

AINextLess integrated
True     63082
False     2355
Name: count, dtype: int64

AINextMuch less integrated
True     64289
False     1148
Name: count, dtype: int64

AIThreat
False    44689
True     20748
Name: count, dtype: int64

AIEthics
False    41548
True     23889
Name: count, dtype: int64

AIChallenges
False    37531
True     27906
Name: count, dtype: int64

TBranch
False    44477
True     20960
Name: count, dtype: int64

ICorPM
True     35636
False    29801
Name: count, dtype: int64

WorkExp
True     35779
False    29658
Name: count, dtype: int64

Knowledge_1
True     36773
False    28664
Name: count, dtype: int64

Knowledge_2
True     37416
False    28021
Name: count, dtype: int64

Knowledge_3
True     37342
False    28095
Name: count, dtype: int64

Knowledge_4
True     37407
False    28030
Name: count, dtype: int64

Knowledge_5
True     37557
False    27880
Name: count, dtype: int64

Knowledge_6
True     37573
False    27864
Name: count, dtype: int64

Knowledge_7
True     37659
False    27778
Name: count, dtype: int64

Knowledge_8
True     37679
False    27758
Name: count, dtype: int64

Knowledge_9
True     37802
False    27635
Name: count, dtype: int64

Frequency_1
True     37068
False    28369
Name: count, dtype: int64

Frequency_2
True     37073
False    28364
Name: count, dtype: int64

Frequency_3
True     37727
False    27710
Name: count, dtype: int64

TimeSearching
True     36526
False    28911
Name: count, dtype: int64

TimeAnswering
True     36593
False    28844
Name: count, dtype: int64

Frustration
True     37186
False    28251
Name: count, dtype: int64

ProfessionalTech
True     37673
False    27764
Name: count, dtype: int64

ProfessionalCloud
True     36946
False    28491
Name: count, dtype: int64

ProfessionalQuestion
True     36630
False    28807
Name: count, dtype: int64

Industry
True     36579
False    28858
Name: count, dtype: int64

JobSatPoints_1
True     36113
False    29324
Name: count, dtype: int64

JobSatPoints_4
True     36044
False    29393
Name: count, dtype: int64

JobSatPoints_5
True     36026
False    29411
Name: count, dtype: int64

JobSatPoints_6
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_7
True     35989
False    29448
Name: count, dtype: int64

JobSatPoints_8
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_9
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_10
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_11
True     35992
False    29445
Name: count, dtype: int64

SurveyLength
False    56182
True      9255
Name: count, dtype: int64

SurveyEase
False    56238
True      9199
Name: count, dtype: int64

ConvertedCompYearly
True     42002
False    23435
Name: count, dtype: int64

JobSat
True     36311
False    29126
Name: count, dtype: int64

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [41]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [42]:
# Write your code here
for country in df['Country'].unique():
    print(country)

United States of America
United Kingdom of Great Britain and Northern Ireland
Canada
Norway
Uzbekistan
Serbia
Poland
Philippines
Bulgaria
Switzerland
India
Germany
Ireland
Italy
Ukraine
Australia
Brazil
Japan
Austria
Iran, Islamic Republic of...
France
Saudi Arabia
Romania
Turkey
Nepal
Algeria
Sweden
Netherlands
Croatia
Pakistan
Czech Republic
Republic of North Macedonia
Finland
Slovakia
Russian Federation
Greece
Israel
Belgium
Mexico
United Republic of Tanzania
Hungary
Argentina
Portugal
Sri Lanka
Latvia
China
Singapore
Lebanon
Spain
South Africa
Lithuania
Viet Nam
Dominican Republic
Indonesia
Kosovo
Morocco
Taiwan
Georgia
San Marino
Tunisia
Bangladesh
Nigeria
Liechtenstein
Denmark
Ecuador
Malaysia
Albania
Azerbaijan
Chile
Ghana
Peru
Bolivia
Egypt
Luxembourg
Montenegro
Cyprus
Paraguay
Kazakhstan
Slovenia
Jordan
Venezuela, Bolivarian Republic of...
Costa Rica
Jamaica
Thailand
Nicaragua
Myanmar
Republic of Korea
Rwanda
Bosnia and Herzegovina
Benin
El Salvador
Zimbabwe
Afghanistan
Estonia
Malta
Uruguay
Belarus
Colombia
Republic of Moldova
Isle of Man
Nomadic
New Zealand
Palestine
Armenia
United Arab Emirates
Maldives
Ethiopia
Fiji
Guatemala
Uganda
Turkmenistan
Mauritius
Kenya
Cuba
Gabon
Bahamas
South Korea
Iceland
Honduras
Hong Kong (S.A.R.)
Lao People's Democratic Republic
Mongolia
Cambodia
Madagascar
Angola
Democratic Republic of the Congo
Syrian Arab Republic
Iraq
Namibia
Senegal
Kyrgyzstan
Zambia
Swaziland
Côte d'Ivoire
Kuwait
Tajikistan
Burundi
Trinidad and Tobago
Mauritania
Sierra Leone
Panama
Somalia
North Korea
Dominica
Guyana
Togo
Oman
Barbados
Andorra
Democratic People's Republic of Korea
Qatar
Sudan
Cameroon
Papua New Guinea
Bahrain
Yemen
Malawi
Burkina Faso
Congo, Republic of the...
Botswana
Guinea-Bissau
Mozambique
Central African Republic
Equatorial Guinea
Suriname
Belize
Libyan Arab Jamahiriya
Cape Verde
Brunei Darussalam
Bhutan
Guinea
Niger
Antigua and Barbuda
Mali
Samoa
Lesotho
Saint Kitts and Nevis
Monaco
Micronesia, Federated States of...
Haiti
nan
Nauru
Liberia
Chad
Djibouti
Solomon Islands

In [43]:
df['EdLevel'].unique()

<StringArray>
[                                                         'Primary/elementary school',
                                       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
                                    'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
                             'Some college/university study without earning a degree',
 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
                                     'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
                                                'Associate degree (A.A., A.S., etc.)',
                                                                     'Something else',
                                                                                  nan]
Length: 9, dtype: str

In [44]:
df['Employment'].unique()

<StringArray>
[                                                                                                                                                          'Employed, full-time',
                                                                                                                                                            'Student, full-time',
                                                                                                                         'Student, full-time;Not employed, but looking for work',
                                                                                                                          'Independent contractor, freelancer, or self-employed',
                                                                                                                                        'Not employed, and not looking for work',
                                                                                                                                        'Employed, full-time;Student, part-time',
                                                                                                      'Employed, full-time;Independent contractor, freelancer, or self-employed',
                                                                                                                                        'Employed, full-time;Student, full-time',
                                                                                                                                                           'Employed, part-time',
                                                                                                                                        'Student, full-time;Employed, part-time',
 ...
                                                                                  'Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
                                                        'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
                                                              'Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time;Employed, part-time',
          'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
 'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
                            'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
                                                                                                                                                    'Student, full-time;Retired',
                                                                                                     'Employed, full-time;Not employed, but looking for work;Student, part-time',
                                                                                                 'Not employed, and not looking for work;Student, part-time;Employed, part-time',
                                                            'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired']
Length: 110, dtype: str

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [46]:
## Write your code here
df['Employment'] = df['Employment'].apply(lambda x: str(x).split(',')[0])
df['Employment'].unique()
# this massively reduces the number of categories for employment, from 110 to 6

<StringArray>
[              'Employed',                'Student', 'Independent contractor',
           'Not employed',    'I prefer not to say',                'Retired']
Length: 6, dtype: str

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [47]:
## Write your code here
employment_encoding = pd.get_dummies(df['Employment'], prefix='Employment')
employment_encoding

,Employment_Employed,Employment_I prefer not to say,Employment_Independent contractor,Employment_Not employed,Employment_Retired,Employment_Student
0,True,False,False,False,False,False
1,True,False,False,False,False,False
2,True,False,False,False,False,False
3,False,False,False,False,False,True
4,False,False,False,False,False,True
...,...,...,...,...,...,...
65432,True,False,False,False,False,False
65433,True,False,False,False,False,False
65434,True,False,False,False,False,False
65435,True,False,False,False,False,False
65436,False,False,False,False,False,True

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [49]:
## Write your code here
missing_counts = df.isna().sum().sort_values(ascending=False)
missing_counts.head(10)

AINextMuch less integrated       64289
AINextLess integrated            63082
AINextNo change                  52939
AINextMuch more integrated       51999
EmbeddedAdmired                  48704
EmbeddedWantToWorkWith           47837
EmbeddedHaveWorkedWith           43223
ConvertedCompYearly              42002
AIToolNot interested in Using    41023
AINextMore integrated            41009
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [ ]:
## Write your code here
import numpy as np
mean = df['ConvertedCompYearly'].mean()
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(mean)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [ ]:
## Write your code here
freq_val = df['RemoteWork'].value_counts().idxmax()
df['RemoteWork'] = df['RemoteWork'].fillna(freq_val)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [54]:
## Write your code here
df['ConvertedCompYearly_MinMax'] = df['ConvertedCompYearly']/df['ConvertedCompYearly'].max()

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [55]:
## Write your code here
df['ConvertedCompYearly'] = np.log(df['ConvertedCompYearly'])

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [ ]:
## Write your code here
# Intern, Entry-Level, Junior, Mid-Level, Senior, Lead
# 6 Levels, bin by 6

0        NaN
1         20
2         37
3          4
4          9
        ...
65432      5
65433    NaN
65434      9
65435      5
65436    NaN
Name: YearsCode, Length: 65437, dtype: str

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.